config/routes.rb
Rails.application.routes.draw do
  resources :appointmentts
  resources :patients
  resources :offices
  resources :physicians
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appointmentt.rb
class Appointmentt < ApplicationRecord
  belongs_to :physician
  belongs_to :patient
end

app/controllers/appointmentts_controller.rb
class AppointmenttsController < ApplicationController
  before_action :set_appointmentt, only: [:show, :edit, :update, :destroy]

  # GET /appointmentts
  # GET /appointmentts.json
  def index
    @appointmentts = Appointmentt.all
  end

  # GET /appointmentts/1
  # GET /appointmentts/1.json
  def show
  end

  # GET /appointmentts/new
  def new
    @appointmentt = Appointmentt.new
  end

  # GET /appointmentts/1/edit
  def edit
  end

  # POST /appointmentts
  # POST /appointmentts.json
  def create
    @appointmentt = Appointmentt.new(appointmentt_params)

    respond_to do |format|
      if @appointmentt.save
        format.html { redirect_to @appointmentt, notice: 'Appointmentt was successfully created.' }
        format.json { render :show, status: :created, location: @appointmentt }
      else
        format.html { render :new }
        format.json { render json: @appointmentt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointmentts/1
  # PATCH/PUT /appointmentts/1.json
  def update
    respond_to do |format|
      if @appointmentt.update(appointmentt_params)
        format.html { redirect_to @appointmentt, notice: 'Appointmentt was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointmentt }
      else
        format.html { render :edit }
        format.json { render json: @appointmentt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointmentts/1
  # DELETE /appointmentts/1.json
  def destroy
    @appointmentt.destroy
    respond_to do |format|
      format.html { redirect_to appointmentts_url, notice: 'Appointmentt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointmentt
      @appointmentt = Appointmentt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointmentt_params
      params.require(:appointmentt).permit(:visit, :physician_id, :patient_id)
    end
end

app/helpers/appointmentts_helper.rb
module AppointmenttsHelper
end

app/views/appointmentts/_form.html.erb
<%= form_with(model: appointmentt, local: true) do |form| %>
  <% if appointmentt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointmentt.errors.count, "error") %> prohibited this appointmentt from being saved:</h2>

      <ul>
        <% appointmentt.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :visit %>
    <%= form.datetime_select :visit %>
  </div>

  <div class="field">
    <%= form.label :physician_id %>
    <%= form.collection_select :physician_id,Physician.all,:id,:name %>
  </div>

  <div class="field">
    <%= form.label :patient_id %>
    <%= form.collection_select :patient_id,Patient.all,:id,:name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointmentts/edit.html.erb
<h1>Editing Appointmentt</h1>

<%= render 'form', appointmentt: @appointmentt %>

<%= link_to 'Show', @appointmentt %> |
<%= link_to 'Back', appointmentts_path %>

app/views/appointmentts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointmentts</h1>

<table>
  <thead>
    <tr>
      <th>Visit</th>
      <th>Physician</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
    
  </thead>

  <tbody>
    <% @appointmentts.each do |appointmentt| %>
      <tr>
        <td><%= appointmentt.visit.to_datetime.to_formatted_s :long_ordinal %></td>
        <td><%= appointmentt.physician.name %></td>
        <td><%= appointmentt.patient.name %></td>
        <td><%= link_to 'Show', appointmentt %></td>
        <td><%= link_to 'Edit', edit_appointmentt_path(appointmentt) %></td>
        <td><%= link_to 'Destroy', appointmentt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointmentt', new_appointmentt_path %>

app/views/appointmentts/new.html.erb
<h1>New Appointmentt</h1>

<%= render 'form', appointmentt: @appointmentt %>

<%= link_to 'Back', appointmentts_path %>

app/views/appointmentts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Visit:</strong>
  <%= @appointmentt.visit.to_datetime.to_formatted_s :long_ordinal
  %>
</p>

<p>
  <strong>Physician:</strong>
  <%= @appointmentt.physician.name %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @appointmentt.patient.name %>
</p>

<%= link_to 'Edit', edit_appointmentt_path(@appointmentt) %> |
<%= link_to 'Back', appointmentts_path %>